version: '2'
services:
    mysql-jira:
       build: mysql
       container_name: mysql-jira
       volumes:
         - /opt/data
       hostname: mysql-jira
       restart: unless-stopped
    jira-fgh:
       build: jira
       container_name: jira-fgh
       depends_on:
         - mysql-jira
       hostname: jira-fgh
       restart: unless-stopped
